### ISSUE TITLE
Combination of fast-syntax-highlighting and prompt reset makes colors disappear

### ISSUE THREAD

**Issue by strindberg** [zdharma/history-search-multi-word#12]
The following `~/.zshrc` is intended to show that coloring in history-search-multi-word disappears when a prompt-reset is scheduled AND fast-syntax-highligting is loaded.

The code below schedules the prompt to be reset each 5 seconds (in my real configuration, some data is of course refreshed, which is the purpose of the reset). As soon as the prompt is reset, the coloring of the selected line in history-search-multi-word disappears. The problem does not manifest itself if fast-syntax-highlighting is not loaded, so there seems to be

 something in the interaction between the two packages that trigger the problem.

Here is a asciinema recording to illustrate what happens: 
https://asciinema.org/a/pMLCDIXGC2irPlXdkE27FqCJ8

```
HISTFILE="$HOME/.zsh_history"

source /opt/sources/history-search-multi-word/history-search-multi-word.plugin.zsh
source /opt/sources/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh

schedprompt() {
    zle && zle reset-prompt
    sched +5 schedprompt
}

zmodload -i zsh/sched
schedprompt
```

**Comment by psprint** [comment]
Could a small donation be granted for this? Like $5. I would sit to this today. It is little demanding to track this, the money would go for a coffee, I need them because I do not work. I have a [PayPal button](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=H4GZAACT2MQ3W)

**Comment by strindberg** [comment]
Contribution done. I'm happy to support all your great work on Zsh.

**Comment by psprint** [comment]
Thanks! It is late today, I will approach this tomorrow or on Sunday

**Comment by psprint** [comment]
I've finished one way of solving this, README part is below, does it help? I'm thinking about adding other protections:

Set:

```zsh
    zstyle :plugin:history-search-multi-word reset-prompt-protect 1
```

to be able to use `zle reset-prompt` in your e.g. `sched` calls, in presence of `zdharma/fast-syntax-highlighting`, `zsh-users/zsh-syntax-highlighting`, `zsh-users/zsh-autosuggestions` and other plugins that hook up into Zshell by overloading Zle widgets. In general, HSMW should be loaded in bulk (no gap) with all those plugins, right before them.

**Comment by strindberg** [comment]
This does seem to solve the problem. I'll do some more testing, but it looks promising.

**Comment by psprint** [comment]
It turned out to be the proper, the best solution. The other one I was curious about, using `zle-line-pre-redraw` Zle widget, turned out to be not possible, the widget isn't called on `reset-prompt`. The same for `zle-line-{init,finish}`. There's one more way, I've [started a thread](http://www.zsh.org/mla/users//2018/msg00513.html) on Zsh mailing list for it, maybe it would yield something.

I was thinking about alternate solution because I loaded HSMW 1 second before F-Sy-Highlighting and jumped with Ctrl-R in between HSMW and FSH a few times. Results are pretty random. I'm using Zplugin with turbo-mode and load plugins after prompt, in 1-second time-slots. After moving HSMW to the same time slot, all was working fine with the `reset-prompt-protect`.

But now again, when I test this after a break, I see it doesn't defend from `zsh-users/zsh-autosuggestions`. It was working before, that's weird. I think I will extend the solution as time passes and I will have some new thoughts on it.

**Comment by psprint** [comment]
I just thought, you can run `.reset-prompt` widget instead of `reset-prompt`. Widgets starting with dot are Zsh original widgets, not overloaded by any plugin (like F-Sy-H), so this should also solve the problem.

**Comment by strindberg** [comment]
That's a great suggestion. I will try that. I will now be away from all computers for a couple of days, so I will report back next weekend.

**Comment by strindberg** [comment]
With your proposed fix, everything seems to be working well now.
